envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DATABASE_URL
  scope: RUN_TIME
  value: ${db.DATABASE_URL}
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
name: webapps-demo
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: SamPolachek/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: webapps-demo-django
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    python manage.py loaddata books.json
    python manage.py build books
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: SamPolachek/PythonWebApps
  name: webapps-demo-static
  routes:
  - path: /static
  source_dir: Superhero/static
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
domains:
  - domain: shrinking-world.com
    type: PRIMARY
    zone: shrinking-world.com
  - domain: seamanslog.com
    type: ALIAS
    zone: seamanslog.com